[build]

cmd = 'go build -gcflags "all=-N -l" -o ./tmp/app'
full_bin = "/go/bin/dlv"
args_bin = ["--listen=:4000", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec", "/app/tmp/app"]
